### ISSUE TITLE
Use with long-reads

### ISSUE THREAD

**Issue by Akazhiel** [PopicLab/cue#2]
Hello!

I'm interested in using this tool in a set of long-read data generated with Nanopore that we have. I've read in the paper that it can be run with different long-reads technologies, but I was wondering if we have to set some specific parameters in the yaml files?

Best regards,

Jonatan

**Comment by viq854** [comment]
Hi Jonatan,

Sorry for the delay in the reply. We don't have support for ONT reads yet. We plan to release a model for this data type in 2023. 

Best,
Vic
