### ISSUE TITLE
How to translate the vcf result to the type same to the type such as manta and delly

### ISSUE THREAD

**Issue by ld9866** [PopicLab/cue#24]
Dear developer:
Very good software, but we currently have two problems in the process of use.
Firstly, we would like to ask whether the trained model can be directly applied to mice, pigs and other species with very similar human genomes.
Secondly, How to translate the vcf result to the type same to the type such as manta and delly? We currently want to do a SV database, and to merge a variety of methods of the results of the file for individual typing, but this step we are not clear how to achieve.
Thank you!
Best day!

**Comment by viq854** [comment]
Hi ld9866,

Thank you for trying out the software and happy to help in getting it to work on your end. To answer your questions:
1. Yes, the software should work on other species as well (I haven't tried that yet though, and would love to hear about your experience).
2. The VCF output lists the event type in the SVTYPE field, consistent with other tools. Is there an example of a record you had trouble with converting/interpreting?

Thank you,
Victoria
