### ISSUE TITLE
KeyError: 'None-HET'

### ISSUE THREAD

**Issue by kuro7766** [PopicLab/cue#26]
``` 
 File "cue/img/datasets.py", line 86, in get_ground_truth_target
    labels.append(constants.SV_LABELS[record.get_sv_type_with_zyg()])
KeyError: 'None-HET'
```

after running `python engine/generate.py --config config/generate.yaml `

**Comment by viq854** [comment]
Hi kuro7766,

It looks like the VCF file provided as ground truth may be missing the type of the SV for a record (is the SVTYPE field missing in your input?).

Best,
Victoria
