### ISSUE TITLE
Error message `_pickle.UnpicklingError: invalid load key, 'v'.` in the SV calling step

### ISSUE THREAD

**Issue by LorenaDerezanin** [PopicLab/cue#3]
Hi, 
I just successfully ran your demo and it worked well on my OS (Linux Manjaro). 
Still, it didn't run the SV calling on the first try, but instead, I got the above error message.

It turns out that the bam file (~170 MB) from the `data/demo/inputs` was not downloaded by default when I first cloned your repo.
Installing `git lfs` before cloning helped solve this problem.

So I just wanted to suggest you add these steps to the README:
Install [git lfs](https://git-lfs.github.com/): `sudo apt-get install git-lfs` (Debian-based Linux distros) 
Set up git lfs: `git lfs install`

prior to the `git clone` step, as the error message is not particularly straightforward with this one.

Looking forward to running Cue on my data in the following days!

Thank you,
Lorena

**Comment by viq854** [comment]
Hi @LorenaDerezanin, thanks for reporting this issue! 

To simplify the workflow (and avoid LFS), the Cue models and data have now been moved to Google Cloud Storage. 
A new model is now also available (along with updates that optimize runtime and RAM usage). 

Let me know if you have any more questions/suggestions!

Thanks,
Victoria
