### ISSUE TITLE
Issue while outputting the svs.vcf file

### ISSUE THREAD

**Issue by sivianil** [PopicLab/cue#9]
<img width="1216" alt="Screenshot 2022-12-13 at 11 59 24" src="https://user-images.githubusercontent.com/75676816/207300148-55538211-e0a1-4465-83b0-3c061bb6b3bc.png">
Unfortunately I can't use python3.7 on my MacOS since it is deprecated. I tried to update all the packages to the recent versions which are compatible with python3.8 or 3.10. I fixed all the bugs arose during the setup. But after running the model, it cannot create variant file due to some error with pysam (Check the screenshot). I tried different versions of pysam 0.18, 0.19.1 and the recent versions. Still running into the same error!.. Do you have any alternate solution? I'm just asking out of the curiosity, did you tried to run this models using python3.8 or 3.10 interpreter and updating the package versions?

Best,
Anil

**Comment by viq854** [comment]
Python 3.7 can be installed from here: https://www.python.org/downloads/macos/. The package versions need to match what is listed in the requirements file for ensure expected performance of the model. Alternatively, you could also use Docker to setup all the requirements (see cue/install/docker/Dockerfile).

**Comment by sivianil** [comment]
Thanks for the quick response! Much appreciated. What about samtools, bcftools and htslib versions?I have 1.16 versions.  It should be compatible with pysam right!!

**Comment by viq854** [comment]
Cue doesn't depend on those tools directly -- only the Python version and the packages listed in the requirements.txt file should match the expected version.

**Comment by sivianil** [comment]
As you mentioned earlier, I need to use python3.7 and the package versions in the requirements.txt file. I followed your instructions and ran the model. But still can't get rid of the error I posted earlier.

**Comment by viq854** [comment]
Could you provide the full command you're running and the versions you currently have installed --  the output of 'pip freeze' in your virtual environment.
